// <auto-generated />
using LaptopStop_MVC.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace LaptopStopMVC.Migrations
{
    [DbContext(typeof(LaptopDbContext))]
    partial class LaptopDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("LaptopStop_MVC.Models.Laptop", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CategoryID");

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.HasKey("ID");

                    b.HasIndex("CategoryID");

                    b.ToTable("Laptops");
                });

            modelBuilder.Entity("LaptopStop_MVC.Models.LaptopCategory", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("ID");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("LaptopStop_MVC.Models.LaptopWishList", b =>
                {
                    b.Property<int>("LaptopID");

                    b.Property<int>("WishListID");

                    b.HasKey("LaptopID", "WishListID");

                    b.HasIndex("WishListID");

                    b.ToTable("LaptopWishLists");
                });

            modelBuilder.Entity("LaptopStop_MVC.Models.WishList", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("ID");

                    b.ToTable("WishLists");
                });

            modelBuilder.Entity("LaptopStop_MVC.Models.Laptop", b =>
                {
                    b.HasOne("LaptopStop_MVC.Models.LaptopCategory", "Category")
                        .WithMany("Laptops")
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("LaptopStop_MVC.Models.LaptopWishList", b =>
                {
                    b.HasOne("LaptopStop_MVC.Models.Laptop", "Laptop")
                        .WithMany("LaptopsWishLists")
                        .HasForeignKey("LaptopID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("LaptopStop_MVC.Models.WishList", "WishList")
                        .WithMany("LaptopsWishLists")
                        .HasForeignKey("WishListID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
